AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  my-excel app

Globals:
  Api:
    BinaryMediaTypes:
      - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      - '*/*'
 
Resources:
  Mylayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Mylayer
      Description: layer with packages
      ContentUri: layers/
      CompatibleRuntimes:
        - nodejs16.x
  excelApp:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 50
      CodeUri: dist/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 1024
      Layers:
        - !Ref Mylayer
      Environment:
        Variables:
          host: !Ref host
          user: !Ref user
          password: !Ref password
          database: !Ref database
      Events:
        exceluploadevent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /upload
            Method: post
        exceldownloadevent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /download
            Method: get

            

    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints: 
        - app.js
        


